# Configuração de ambiente de desenvolvimento
spring:
  datasource:
    url: jdbc:h2:mem:springrailway # conexão com o banco h2
    username: sa
    password:
  jpa:
    show-sql: true # deixar mais verboso
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2: # configuração do h2-console pra acessar o banco via browser
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false